"use client";

import { useEffect, useMemo, useState } from "react";
import type { Order, Priority, Sector } from "@/lib/pcp-types";
import { dueLabel, initials, shortDateOnlyLabel, targetDateForOrder } from "@/lib/pcp-formatters";
import { AppIcon } from "@/components/ui/AppIcon";

export type OrderFamilyView = { parentOp: string; orders: Order[]; hasSubOrders: boolean };
type QuickFilter = "all" | "late" | "today" | "unassigned" | "paused";
function responsibleName(order: Order) { return order.consultant_name?.trim() || "Não definido"; }
function normalizedResponsibleName(value: string | null | undefined) { return value?.trim().toLocaleUpperCase("pt-BR") || ""; }
function targetDateLabel(order: Order) { return shortDateOnlyLabel(targetDateForOrder(order.installation_scheduled_at, order.delivery_date)); }
function isLate(order: Order) { return dueLabel(order.delivery_date).startsWith("Atrasado"); }
function isToday(order: Order) { return order.delivery_date === new Date().toISOString().slice(0, 10); }

export function OrdersView({ search,responsibleFilter,unassignedResponsibleValue,consultantOptions,families,visibleOrderCount,sectors,expandedFamilies,onSearchChange,onResponsibleFilterChange,onClearFilters,onToggleFamily,onOpenOrder,onBulkUpdate }: {
  search:string; responsibleFilter:string; unassignedResponsibleValue:string; consultantOptions:string[]; families:OrderFamilyView[]; visibleOrderCount:number; sectors:Sector[]; expandedFamilies:Set<string>;
  onSearchChange:(value:string)=>void; onResponsibleFilterChange:(value:string)=>void; onClearFilters:()=>void; onToggleFamily:(parentOp:string)=>void; onOpenOrder:(order:Order)=>void;
  onBulkUpdate:(orderIds:string[], patch:{ consultant_name?:string|null; priority?:Priority })=>Promise<boolean>;
}) {
  const [quickFilter,setQuickFilter]=useState<QuickFilter>(()=>{if(typeof window==="undefined")return "all";const value=new URLSearchParams(window.location.search).get("orders_filter");return (["late","today","unassigned","paused"] as string[]).includes(value||"")?value as QuickFilter:"all";});
  const [selected,setSelected]=useState<Set<string>>(new Set());
  const [page,setPage]=useState(1); const [bulkBusy,setBulkBusy]=useState(false);
  const pageSize=25;
  const filteredFamilies=useMemo(()=>families.filter((family)=>quickFilter==="all"||family.orders.some((order)=>quickFilter==="late"?isLate(order):quickFilter==="today"?isToday(order):quickFilter==="unassigned"?!order.consultant_name?.trim():order.status==="paused")),[families,quickFilter]);
  const pageCount=Math.max(1,Math.ceil(filteredFamilies.length/pageSize));
  const pageFamilies=filteredFamilies.slice((page-1)*pageSize,page*pageSize);
  useEffect(()=>{setPage(1);setSelected(new Set());},[search,responsibleFilter,quickFilter]);
  useEffect(()=>{const url=new URL(window.location.href);quickFilter==="all"?url.searchParams.delete("orders_filter"):url.searchParams.set("orders_filter",quickFilter);window.history.replaceState(window.history.state,"",`${url.pathname}${url.search}`)},[quickFilter]);
  useEffect(()=>{if(page>pageCount)setPage(pageCount)},[page,pageCount]);
  const pageOrderIds=pageFamilies.flatMap((family)=>family.orders.map((order)=>order.id));
  const allPageSelected=pageOrderIds.length>0&&pageOrderIds.every((id)=>selected.has(id));
  function toggle(id:string){setSelected((current)=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
  function togglePage(){setSelected((current)=>{const next=new Set(current);if(allPageSelected)pageOrderIds.forEach((id)=>next.delete(id));else pageOrderIds.forEach((id)=>next.add(id));return next})}
  async function applyBulk(patch:{consultant_name?:string|null;priority?:Priority}){if(!selected.size||bulkBusy)return;setBulkBusy(true);const ok=await onBulkUpdate([...selected],patch);if(ok)setSelected(new Set());setBulkBusy(false)}
  function exportCsv(){const orders=filteredFamilies.flatMap((family)=>family.orders);const rows=[["OP","Cliente","Serviço","Setor","Responsável","Prioridade","Prazo"],...orders.map((order)=>[order.op_number,order.client_name,order.description,sectors.find((sector)=>sector.id===order.sector_id)?.name||"",responsibleName(order),order.priority,order.delivery_date])];const csv=rows.map((row)=>row.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`pedidos-publicolor-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}

  return <section className="management-view orders-management-view orders-v34">
    <div className="view-toolbar orders-view-toolbar"><label className="orders-search-field"><AppIcon name="search"/><input value={search} onChange={(event)=>onSearchChange(event.target.value)} placeholder="Buscar OP, cliente, serviço ou responsável…"/></label><label className="orders-responsible-filter"><span>Responsável</span><select value={responsibleFilter} onChange={(event)=>onResponsibleFilterChange(event.target.value)}><option value="all">Todos</option><option value={unassignedResponsibleValue}>Sem responsável</option>{consultantOptions.map((consultant)=><option key={consultant} value={normalizedResponsibleName(consultant)}>{consultant}</option>)}</select></label>{(search||responsibleFilter!=="all"||quickFilter!=="all")&&<button type="button" className="orders-clear-filter" onClick={()=>{onClearFilters();setQuickFilter("all")}}>Limpar</button>}<button type="button" className="icon-text-button" onClick={exportCsv}><AppIcon name="download"/> Exportar</button><span>{filteredFamilies.length} OP(s) · {visibleOrderCount} pedido(s)</span></div>
    <div className="orders-quick-filters" role="group" aria-label="Filtros rápidos">{([['all','Todos'],['late','Atrasados'],['today','Hoje'],['unassigned','Sem responsável'],['paused','Pausados']] as Array<[QuickFilter,string]>).map(([key,label])=><button key={key} className={quickFilter===key?"active":""} onClick={()=>setQuickFilter(key)}>{label}</button>)}</div>
    {selected.size>0&&<div className="orders-bulk-bar"><b>{selected.size} selecionado(s)</b><label>Responsável<select defaultValue="" disabled={bulkBusy} onChange={(event)=>{if(event.target.value)void applyBulk({consultant_name:event.target.value});event.currentTarget.value=""}}><option value="">Alterar…</option><option value="__none__">Sem responsável</option>{consultantOptions.map((name)=><option key={name} value={name}>{name}</option>)}</select></label><label>Prioridade<select defaultValue="" disabled={bulkBusy} onChange={(event)=>{if(event.target.value)void applyBulk({priority:event.target.value as Priority});event.currentTarget.value=""}}><option value="">Alterar…</option><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><button onClick={()=>setSelected(new Set())} disabled={bulkBusy}>Cancelar</button></div>}
    <div className="responsive-table grouped-orders-table"><div className="table-head"><span><input type="checkbox" aria-label="Selecionar página" checked={allPageSelected} onChange={togglePage}/> OP</span><span>Cliente e serviço</span><span>Setor</span><span>Responsável</span><span>Instalação / entrega</span><span>Ação</span></div>{pageFamilies.map((family)=>{
      const isFamily=family.hasSubOrders||family.orders.length>1;const isExpanded=expandedFamilies.has(family.parentOp);const firstOrder=family.orders[0];const clientsInFamily=[...new Set(family.orders.map((order)=>order.client_name))];const sectorNames=[...new Set(family.orders.map((order)=>sectors.find((sector)=>sector.id===order.sector_id)?.name||"—"))];const responsibleNames=[...new Set(family.orders.map(responsibleName))];const familyResponsible=responsibleNames.length===1?responsibleNames[0]:`${responsibleNames.length} responsáveis`;const nextDeliveryOrder=[...family.orders].sort((a,b)=>targetDateForOrder(a.installation_scheduled_at,a.delivery_date).localeCompare(targetDateForOrder(b.installation_scheduled_at,b.delivery_date)))[0];const familyIsLate=family.orders.some(isLate);const familyId=`order-family-${firstOrder.id}`;const familySelected=family.orders.every((order)=>selected.has(order.id));
      return <div className={`order-family ${isExpanded?"expanded":""}`} key={family.parentOp}><article className={`table-row order-parent-row ${isFamily?"has-children":"single-order"}`}><b className="order-parent-op"><input type="checkbox" aria-label={`Selecionar OP ${family.parentOp}`} checked={familySelected} onChange={()=>setSelected((current)=>{const next=new Set(current);family.orders.forEach((order)=>familySelected?next.delete(order.id):next.add(order.id));return next})}/>{isFamily&&<button type="button" className="order-family-toggle" aria-expanded={isExpanded} aria-controls={familyId} onClick={()=>onToggleFamily(family.parentOp)}><AppIcon name={isExpanded?"chevronDown":"chevronRight"}/></button>}OP {family.parentOp}<small>{family.orders.length} item(ns)</small></b><div className="order-client-cell"><strong>{clientsInFamily.length===1?clientsInFamily[0]:`${clientsInFamily.length} clientes`}</strong><small>{isFamily?`Pedido principal com ${family.orders.length} subpedidos.`:firstOrder.description}</small></div><span className="order-sector-cell">{sectorNames.length===1?sectorNames[0]:`${sectorNames.length} setores`}</span><span className="order-responsible-cell"><i>{initials(familyResponsible)}</i><b>{familyResponsible}</b></span><span className={`order-delivery-cell ${familyIsLate?"table-late":""}`}><b>{isFamily?`Próxima: ${targetDateLabel(nextDeliveryOrder)}`:targetDateLabel(firstOrder)}</b><small>Produção: {isFamily?dueLabel(nextDeliveryOrder.delivery_date):dueLabel(firstOrder.delivery_date)}</small></span><button type="button" onClick={()=>isFamily?onToggleFamily(family.parentOp):onOpenOrder(firstOrder)}>{isFamily?(isExpanded?"Recolher":"Abrir itens"):"Ver pedido"}</button></article>{isFamily&&isExpanded&&<div className="order-family-children" id={familyId}>{family.orders.map((order)=><article className="table-row order-child-row" key={order.id}><b className="order-child-op"><input type="checkbox" checked={selected.has(order.id)} aria-label={`Selecionar OP ${order.op_number}`} onChange={()=>toggle(order.id)}/><span>↳</span> OP {order.op_number}</b><div className="order-client-cell"><strong>{order.client_name}</strong><small>{order.description}</small></div><span className="order-sector-cell">{sectors.find((sector)=>sector.id===order.sector_id)?.name||"—"}</span><span className="order-responsible-cell"><i>{initials(responsibleName(order))}</i><b>{responsibleName(order)}</b></span><span className={`order-delivery-cell ${isLate(order)?"table-late":""}`}><b>{targetDateLabel(order)}</b><small>Produção: {dueLabel(order.delivery_date)}</small></span><button type="button" onClick={()=>onOpenOrder(order)}>Ver pedido</button></article>)}</div>}</div>})}</div>
    {!filteredFamilies.length&&<div className="view-empty">Nenhum pedido ativo encontrado.</div>}
    {pageCount>1&&<nav className="pagination-bar"><button disabled={page===1} onClick={()=>setPage((current)=>current-1)}>Anterior</button><span>Página {page} de {pageCount}</span><button disabled={page===pageCount} onClick={()=>setPage((current)=>current+1)}>Próxima</button></nav>}
  </section>;
}
