"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { dateOnlyLabel, dueLabel, installationDateTimeLabel, targetDateForOrder, toInstallationInputValue } from "@/lib/pcp-formatters";
import type { DetailTab, Order, Sector } from "@/lib/pcp-types";
import { supabase } from "@/lib/supabase";
import { AppIcon } from "@/components/ui/AppIcon";

type Props = { orders: Order[]; sectors: Sector[]; installationSector: Sector | null; productionCompletedSector: Sector | null; canOperate: boolean; busyOrderId: string | null; onOpenOrder: (order: Order, tab: DetailTab) => void; onSchedule: (event: FormEvent<HTMLFormElement>, order: Order) => void };
type AgendaView = "month" | "week" | "day";
const WEEK_DAYS = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
function dateKey(date: Date) { return [date.getUTCFullYear(),String(date.getUTCMonth()+1).padStart(2,"0"),String(date.getUTCDate()).padStart(2,"0")].join("-"); }
function currentManausDateKey() { return new Intl.DateTimeFormat("en-CA", { timeZone:"America/Manaus", year:"numeric", month:"2-digit", day:"2-digit" }).format(new Date()); }
function monthKey(value: string) { return value.slice(0,7); }
function monthDate(value: string) { const [year,month] = value.split("-").map(Number); return new Date(Date.UTC(year,month-1,1)); }
function moveMonth(value: string, amount: number) { const date=monthDate(value); date.setUTCMonth(date.getUTCMonth()+amount); return dateKey(date).slice(0,7); }
function monthLabel(value: string) { return monthDate(value).toLocaleDateString("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}); }
function calendarDays(value: string) { const first=monthDate(value); const start=new Date(first); start.setUTCDate(start.getUTCDate()-first.getUTCDay()); return Array.from({length:42},(_,index)=>{const day=new Date(start);day.setUTCDate(start.getUTCDate()+index);return{key:dateKey(day),dayNumber:day.getUTCDate(),inMonth:day.getUTCMonth()===first.getUTCMonth()};}); }
function targetDate(order: Order) { return targetDateForOrder(order.installation_scheduled_at,order.delivery_date); }
function weekDates(selected: string) { const date=new Date(`${selected}T12:00:00Z`); date.setUTCDate(date.getUTCDate()-date.getUTCDay()); return Array.from({length:7},(_,i)=>{const next=new Date(date);next.setUTCDate(date.getUTCDate()+i);return dateKey(next);}); }
function normalize(value: string | null | undefined) { return String(value || "").trim().toLocaleLowerCase("pt-BR"); }
function pendingPriority(order: Order) { const rank = order.priority === "urgent" ? 0 : order.priority === "high" ? 1 : order.priority === "normal" ? 2 : 3; return `${rank}:${targetDate(order)}:${order.op_number}`; }
async function copyText(value: string) { if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(value); const area=document.createElement("textarea");area.value=value;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove(); }

export function InstallationAgendaView({ orders,sectors,installationSector,productionCompletedSector,canOperate,busyOrderId,onOpenOrder,onSchedule }: Props) {
  const today=currentManausDateKey();
  const [visibleMonth,setVisibleMonth]=useState(monthKey(today));
  const [selectedDate,setSelectedDate]=useState(today);
  const [view,setView]=useState<AgendaView>("month");
  const [teamFilter,setTeamFilter]=useState("all");
  const [vehicleFilter,setVehicleFilter]=useState("all");
  const [dailyCapacity,setDailyCapacity]=useState(8);
  const [copied,setCopied]=useState(false);
  useEffect(()=>{ void supabase.from("operational_settings").select("setting_value").eq("setting_key","installation_daily_capacity").maybeSingle().then(({data})=>{const value=Number(data?.setting_value);if(Number.isFinite(value)&&value>0)setDailyCapacity(value);}); },[]);

  const calendarOrders=useMemo(()=>orders.filter((order)=>order.status!=="completed"&&order.sector_id===installationSector?.id&&Boolean(order.installation_scheduled_at)),[orders,installationSector]);
  const filteredOrders=useMemo(()=>calendarOrders.filter((order)=>teamFilter==="all"||normalize(order.installation_team)===normalize(teamFilter)).filter((order)=>vehicleFilter==="all"||normalize(order.installation_vehicle)===normalize(vehicleFilter)),[calendarOrders,teamFilter,vehicleFilter]);
  const ordersByDate=useMemo(()=>{const grouped=new Map<string,Order[]>();filteredOrders.forEach((order)=>{const key=targetDate(order);const entries=grouped.get(key)||[];entries.push(order);grouped.set(key,entries);});grouped.forEach((entries)=>entries.sort((a,b)=>(new Date(a.installation_scheduled_at||0).getTime()-new Date(b.installation_scheduled_at||0).getTime())||a.op_number.localeCompare(b.op_number,"pt-BR",{numeric:true})));return grouped;},[filteredOrders]);
  const teams=useMemo(()=>Array.from(new Set(calendarOrders.map((o)=>o.installation_team?.trim()).filter(Boolean) as string[])).sort(),[calendarOrders]);
  const vehicles=useMemo(()=>Array.from(new Set(calendarOrders.map((o)=>o.installation_vehicle?.trim()).filter(Boolean) as string[])).sort(),[calendarOrders]);
  const days=useMemo(()=>calendarDays(visibleMonth),[visibleMonth]);
  const selectedOrders=ordersByDate.get(selectedDate)||[];
  const week=useMemo(()=>weekDates(selectedDate),[selectedDate]);
  const queueWithoutTime=useMemo(()=>filteredOrders.filter((order)=>order.installation_scheduled_at&&!order.installation_time_confirmed).slice(0,20),[filteredOrders]);
  const conflicts=useMemo(()=>{const ids=new Set<string>();selectedOrders.forEach((order,index)=>selectedOrders.slice(index+1).forEach((other)=>{if(!order.installation_time_confirmed||!other.installation_time_confirmed)return;const first=new Date(order.installation_scheduled_at!).getTime();const second=new Date(other.installation_scheduled_at!).getTime();const near=Math.abs(first-second)<2*60*60*1000;const sameTeam=normalize(order.installation_team)&&normalize(order.installation_team)===normalize(other.installation_team);const sameVehicle=normalize(order.installation_vehicle)&&normalize(order.installation_vehicle)===normalize(other.installation_vehicle);if(near&&(sameTeam||sameVehicle)){ids.add(order.id);ids.add(other.id);}}));return ids;},[selectedOrders]);
  const pendingScheduling=useMemo(()=>orders.filter((order)=>order.status!=="completed"&&order.sector_id===productionCompletedSector?.id).sort((a,b)=>pendingPriority(a).localeCompare(pendingPriority(b),"pt-BR",{numeric:true})),[orders,productionCompletedSector]);
  const scheduledCount=calendarOrders.length;
  const inInstallationCount=orders.filter((o)=>o.sector_id===installationSector?.id).length;
  const monthOrderCount=Array.from(ordersByDate.entries()).filter(([key])=>monthKey(key)===visibleMonth).reduce((sum,[,entries])=>sum+entries.length,0);

  function goToToday(){setVisibleMonth(monthKey(today));setSelectedDate(today);} function selectDay(key:string){setSelectedDate(key);setVisibleMonth(monthKey(key));}
  async function copyRoute(){const lines=selectedOrders.map((order,index)=>`${index+1}. ${order.installation_time_confirmed&&order.installation_scheduled_at?new Date(order.installation_scheduled_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Manaus"}):"Horário a definir"} — OP ${order.op_number} — ${order.client_name}\n${order.installation_address||"Endereço não informado"}`);await copyText(lines.join("\n\n"));setCopied(true);window.setTimeout(()=>setCopied(false),1800);}

  return <section className="installation-agenda installation-calendar-view v34-agenda">
    <div className="agenda-summary agenda-summary-responsive agenda-summary-five"><article className={pendingScheduling.length?"attention":""}><small>PENDENTES DE AGENDAMENTO</small><strong>{pendingScheduling.length}</strong></article><article><small>NO SETOR INSTALAÇÃO</small><strong>{inInstallationCount}</strong></article><article><small>AGENDADOS</small><strong>{scheduledCount}</strong></article><article><small>NO MÊS EXIBIDO</small><strong>{monthOrderCount}</strong></article><article className={selectedOrders.length>dailyCapacity?"capacity-exceeded":""}><small>CAPACIDADE DO DIA</small><strong>{selectedOrders.length}/{dailyCapacity}</strong></article></div>
    <section className="agenda-pending-scheduling"><header><div><small>PRODUÇÃO CONCLUÍDA</small><h2>Pendentes de agendamento</h2><p>Todo pedido neste setor precisa ter data e hora confirmadas para entrar em Instalação.</p></div><span>{pendingScheduling.length}</span></header>{pendingScheduling.length?<div className="agenda-pending-grid">{pendingScheduling.map((order)=><article key={order.id} className={dueLabel(order.delivery_date).startsWith("Atrasado")?"late":""}><div className="agenda-pending-order-info"><div className="agenda-pending-order-title"><b>OP {order.op_number}</b><span>{order.priority === "urgent" ? "Urgente" : order.priority === "high" ? "Alta" : "Normal"}</span></div><h3>{order.client_name}</h3><p>{order.description}</p><small>Prazo de produção: {dateOnlyLabel(order.delivery_date)} · {dueLabel(order.delivery_date)}</small>{order.installation_scheduled_at&&<em>Data anterior: {installationDateTimeLabel(order.installation_scheduled_at)} — confirme ou altere.</em>}</div>{canOperate?<form onSubmit={(event)=>onSchedule(event,order)}><label><span>Data e hora *</span><input type="datetime-local" name="scheduled_at" defaultValue={toInstallationInputValue(order.installation_scheduled_at)||""} required/></label><div><button type="button" onClick={()=>onOpenOrder(order,"installation")}><AppIcon name="eye"/> Abrir</button><button type="submit" className="primary" disabled={busyOrderId===order.id}>{busyOrderId===order.id?"Agendando…":order.installation_scheduled_at?"Confirmar e mover":"Agendar e mover"}</button></div></form>:<button type="button" onClick={()=>onOpenOrder(order,"installation")}><AppIcon name="eye"/> Abrir pedido</button>}</article>)}</div>:<div className="agenda-pending-empty"><AppIcon name="check"/><div><b>Nenhum pedido pendente</b><p>Pedidos concluídos na produção aparecerão aqui até receberem data e hora.</p></div></div>}</section>

    <div className="agenda-control-bar"><div className="page-section-tabs" role="tablist"><button className={view==="month"?"active":""} onClick={()=>setView("month")}>Mês</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>Semana</button><button className={view==="day"?"active":""} onClick={()=>setView("day")}>Dia</button></div><label>Equipe<select value={teamFilter} onChange={(e)=>setTeamFilter(e.target.value)}><option value="all">Todas</option>{teams.map((item)=><option key={item}>{item}</option>)}</select></label><label>Veículo<select value={vehicleFilter} onChange={(e)=>setVehicleFilter(e.target.value)}><option value="all">Todos</option>{vehicles.map((item)=><option key={item}>{item}</option>)}</select></label><button onClick={()=>void copyRoute()} disabled={!selectedOrders.length}><AppIcon name="copy"/>{copied?"Copiado":"Copiar roteiro"}</button></div>

    {queueWithoutTime.length>0&&<section className="agenda-unscheduled-queue"><header><div><small>FILA DE PROGRAMAÇÃO</small><h3>Data definida, horário pendente</h3></div><span>{queueWithoutTime.length}</span></header><div>{queueWithoutTime.map((order)=><button key={order.id} onClick={()=>{selectDay(targetDate(order));setView("day");}}><b>OP {order.op_number}</b><span>{order.client_name}</span><small>{dateOnlyLabel(targetDate(order))}</small></button>)}</div></section>}

    {view==="week"&&<section className="agenda-week-view">{week.map((key)=>{const entries=ordersByDate.get(key)||[];return <article key={key} className={key===selectedDate?"selected":""}><button onClick={()=>selectDay(key)}><small>{WEEK_DAYS[new Date(`${key}T12:00:00Z`).getUTCDay()]}</small><strong>{key.slice(8)}</strong><span>{entries.length}/{dailyCapacity}</span></button><div>{entries.slice(0,5).map((order)=><button key={order.id} onClick={()=>onOpenOrder(order,"installation")}><b>{order.installation_time_confirmed&&order.installation_scheduled_at?new Date(order.installation_scheduled_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Manaus"}):"--:--"}</b><span>OP {order.op_number}</span><small>{order.client_name}</small></button>)}</div></article>;})}</section>}

    <div className={`agenda-calendar-layout ${view==="day"?"day-only":""}`}>
      {view==="month"&&<section className="agenda-calendar-panel"><header className="agenda-calendar-toolbar"><div><small>AGENDA DE INSTALAÇÃO E ENTREGA</small><h2>{monthLabel(visibleMonth)}</h2></div><div className="agenda-calendar-navigation"><button onClick={()=>setVisibleMonth(moveMonth(visibleMonth,-1))}>‹</button><button className="today-button" onClick={goToToday}>Hoje</button><button onClick={()=>setVisibleMonth(moveMonth(visibleMonth,1))}>›</button></div></header><div className="agenda-weekdays">{WEEK_DAYS.map((day)=><span key={day}>{day}</span>)}</div><div className="agenda-month-grid">{days.map((day)=>{const entries=ordersByDate.get(day.key)||[];const exceeded=entries.length>dailyCapacity;return <button key={day.key} className={`${day.inMonth?"in-month":"outside-month"} ${day.key===selectedDate?"selected":""} ${day.key===today?"today":""} ${entries.length?"has-orders":""} ${exceeded?"capacity-exceeded":""}`} onClick={()=>selectDay(day.key)}><span className="calendar-day-number">{day.dayNumber}</span>{entries.length>0&&<span className="calendar-order-marker"><i/><b>{entries.length}</b></span>}</button>;})}</div></section>}

      <section className="agenda-selected-day"><header><div><small>PEDIDOS DO DIA</small><h2>{dateOnlyLabel(selectedDate)}</h2></div><span className={selectedOrders.length>dailyCapacity?"capacity-exceeded":""}>{selectedOrders.length}/{dailyCapacity}</span></header>{selectedOrders.length?<div className="agenda-day-orders">{selectedOrders.map((order)=>{const currentSectorName=sectors.find((s)=>s.id===order.sector_id)?.name||"Setor não identificado";const hasConflict=conflicts.has(order.id);return <article className={`agenda-day-order-card ${hasConflict?"has-conflict":""}`} key={order.id}><div className="agenda-day-order-heading"><div><b>OP {order.op_number}</b><h3>{order.client_name}</h3><p>{order.description}</p></div><time>{order.installation_time_confirmed&&order.installation_scheduled_at?new Date(order.installation_scheduled_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Manaus"}):"Horário a definir"}</time></div>{hasConflict&&<div className="agenda-conflict-alert"><AppIcon name="alert"/>Conflito de equipe ou veículo em horário próximo.</div>}<div className="agenda-order-details"><span><small>PRODUÇÃO</small><b className={dueLabel(order.delivery_date).startsWith("Atrasado")?"late":""}>{dueLabel(order.delivery_date)}</b></span><span><small>SETOR ATUAL</small><b>{order.sector_id===installationSector?.id?"INSTALAÇÃO":currentSectorName}</b></span><span><small>EQUIPE</small><b>{order.installation_team||"Não definida"}</b></span><span><small>VEÍCULO</small><b>{order.installation_vehicle||"Não definido"}</b></span></div>{canOperate?<form className="agenda-reschedule-form" onSubmit={(event)=>onSchedule(event,order)}><label>Data e hora<input key={`${order.id}:${order.installation_scheduled_at||"new"}`} type="datetime-local" name="scheduled_at" defaultValue={toInstallationInputValue(order.installation_scheduled_at)||`${targetDate(order)}T08:00`} required/></label><button type="submit" className="primary" disabled={busyOrderId===order.id}>{busyOrderId===order.id?"Salvando…":order.installation_time_confirmed?"Reagendar":"Definir horário"}</button></form>:<p className="agenda-readonly-date">{order.installation_time_confirmed&&order.installation_scheduled_at?installationDateTimeLabel(order.installation_scheduled_at):`Data prevista: ${dateOnlyLabel(targetDate(order))} · horário não definido`}</p>}<button className="agenda-open-order" onClick={()=>onOpenOrder(order,"installation")}><AppIcon name="eye"/> Abrir pedido</button></article>;})}</div>:<div className="agenda-day-empty"><span>○</span><b>Nenhuma instalação ou entrega neste dia</b><p>Selecione outro dia marcado no calendário.</p></div>}</section>
    </div>
    {!productionCompletedSector&&<div className="agenda-sector-warning">O setor especial PRODUÇÃO CONCLUÍDA não está ativo. A lista de pendentes não poderá ser formada.</div>}{!installationSector&&<div className="agenda-sector-warning">O setor especial INSTALAÇÃO não está ativo. Novos agendamentos ficarão bloqueados.</div>}
  </section>;
}
