"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { dueLabel, shortDateOnlyLabel, targetDateForOrder } from "@/lib/pcp-formatters";
import type { Order, Sector } from "@/lib/pcp-types";
import { AppIcon } from "@/components/ui/AppIcon";
import { supabase } from "@/lib/supabase";

type Props = { search:string; orders:Order[]; sectors:Sector[]; canOperate:boolean; onSearchChange:(value:string)=>void; onOpenHistory:(order:Order)=>void; onReopen:(order:Order)=>void };
const PAGE_SIZE=24;
const columns="id,op_number,client_id,client_name,description,delivery_date,priority,sector_id,status,responsible_user_id,consultant_name,main_image_path,blocked,completed_at,installation_scheduled_at,installation_address,installation_team,installation_vehicle,installation_status,installation_notes,installation_completed_at,installation_time_confirmed,materials,notes,created_at,updated_at,sector_entered_at";
function csvCell(value:unknown){return `"${String(value??"").replace(/"/g,'""')}"`}
function sinceDate(period:"90"|"365"|"all"){if(period==="all")return null;return new Date(Date.now()-Number(period)*86400000).toISOString()}

export function CompletedOrdersView({search,orders,sectors,canOperate,onSearchChange,onOpenHistory,onReopen}:Props){
  const [period,setPeriod]=useState<"90"|"365"|"all">("90");const [page,setPage]=useState(1);const [responsible,setResponsible]=useState("all");const [sector,setSector]=useState("all");const [rows,setRows]=useState<Order[]>([]);const [count,setCount]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const responsibleOptions=useMemo(()=>Array.from(new Set([...orders,...rows].map((order)=>order.consultant_name?.trim()).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,"pt-BR")),[orders,rows]);
  const load=useCallback(async()=>{setLoading(true);setError("");let query=supabase.from("orders").select(columns,{count:"exact"}).eq("status","completed").order("completed_at",{ascending:false,nullsFirst:false}).range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1);const since=sinceDate(period);if(since)query=query.gte("completed_at",since);if(responsible!=="all")query=query.eq("consultant_name",responsible);if(sector!=="all")query=query.eq("sector_id",sector);const term=search.trim().replace(/[,%()]/g," ");if(term)query=query.or(`op_number.ilike.%${term}%,client_name.ilike.%${term}%,description.ilike.%${term}%,consultant_name.ilike.%${term}%`);const result=await query;if(result.error)setError(result.error.message);else{setRows((result.data||[]) as Order[]);setCount(result.count||0)}setLoading(false)},[page,period,responsible,search,sector]);
  useEffect(()=>{setPage(1)},[period,responsible,search,sector]);useEffect(()=>{void load()},[load]);
  useEffect(()=>{const channel=supabase.channel(`completed-orders-${Date.now()}`).on("postgres_changes",{event:"*",schema:"public",table:"orders"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
  const pageCount=Math.max(1,Math.ceil(count/PAGE_SIZE));
  async function exportCsv(){setLoading(true);let query=supabase.from("orders").select(columns).eq("status","completed").order("completed_at",{ascending:false}).limit(5000);const since=sinceDate(period);if(since)query=query.gte("completed_at",since);if(responsible!=="all")query=query.eq("consultant_name",responsible);if(sector!=="all")query=query.eq("sector_id",sector);const term=search.trim().replace(/[,%()]/g," ");if(term)query=query.or(`op_number.ilike.%${term}%,client_name.ilike.%${term}%,description.ilike.%${term}%`);const {data,error:exportError}=await query;if(exportError){setError(exportError.message);setLoading(false);return}const header=["OP","Cliente","Serviço","Responsável","Setor final","Concluído em","Instalação/entrega"];const lines=((data||[]) as Order[]).map((order)=>[order.op_number,order.client_name,order.description,order.consultant_name||"",sectors.find((item)=>item.id===order.sector_id)?.name||"",order.completed_at||"",targetDateForOrder(order.installation_scheduled_at,order.delivery_date)]);const blob=new Blob(["\uFEFF"+[header,...lines].map((row)=>row.map(csvCell).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`publicolor-concluidos-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url);setLoading(false)}
  return <section className="management-view completed-management-view"><div className="view-toolbar completed-toolbar"><label><AppIcon name="search"/><input value={search} onChange={(event)=>onSearchChange(event.target.value)} placeholder="Buscar nos concluídos…"/></label><select value={period} onChange={(event)=>setPeriod(event.target.value as typeof period)}><option value="90">Últimos 90 dias</option><option value="365">Último ano</option><option value="all">Todo o histórico</option></select><select value={responsible} onChange={(event)=>setResponsible(event.target.value)}><option value="all">Todos os responsáveis</option>{responsibleOptions.map((item)=><option key={item}>{item}</option>)}</select><select value={sector} onChange={(event)=>setSector(event.target.value)}><option value="all">Todos os setores finais</option>{sectors.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" onClick={()=>void exportCsv()} disabled={!count||loading}><AppIcon name="download"/> Exportar CSV</button><span>{loading?"Atualizando…":`${count} concluídos`}</span></div>{error&&<div className="db-alert"><b>Falha ao consultar</b><span>{error}</span></div>}{rows.length?<div className="completed-cards-grid">{rows.map((order)=>{const sectorName=sectors.find((item)=>item.id===order.sector_id)?.name||"Concluído";return <article className="completed-order-card" key={order.id}><header className="completed-card-header"><div><span className="completed-card-label">ORDEM DE SERVIÇO</span><strong>OP {order.op_number}</strong></div><span className="completed-card-status">Concluído</span></header><div className="completed-card-body"><section className="completed-card-client"><small>CLIENTE E SERVIÇO</small><h3>{order.client_name}</h3><p>{order.description}</p></section><section className="completed-card-info-grid"><div><small>SETOR FINAL</small><strong>{sectorName}</strong><em>{order.consultant_name||"Sem responsável"}</em></div><div><small>INSTALAÇÃO / ENTREGA</small><strong>{shortDateOnlyLabel(targetDateForOrder(order.installation_scheduled_at,order.delivery_date))}</strong><em>Produção: {dueLabel(order.delivery_date)}</em></div></section></div><footer className="completed-card-actions"><button type="button" className="completed-history-button" onClick={()=>onOpenHistory(order)}><AppIcon name="refresh"/><b>Histórico</b></button>{canOperate&&<button type="button" className="completed-reopen-button" onClick={()=>onReopen(order)}><AppIcon name="refresh"/><b>Reabrir</b></button>}</footer></article>})}</div>:!loading&&<div className="view-empty"><b>Nenhum pedido concluído</b><span>Altere os filtros ou o período.</span></div>}<nav className="pagination-bar"><button disabled={page<=1||loading} onClick={()=>setPage((value)=>value-1)}>Anterior</button><span>Página {page} de {pageCount}</span><button disabled={page>=pageCount||loading} onClick={()=>setPage((value)=>value+1)}>Próxima</button></nav></section>
}
